### ISSUE TITLE
Frontend build:prod error

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/UpGrade#81]
Caused by 1eb32f6c 

Steps to reproduce:
`npm ci`
`npm run build:prod`

```
ERROR in projects/abtesting/src/app/core/local-storage/local-storage.service.spec.ts(46,7): error TS2322: Type '{ ids: undefined[]; entities: {}; isLoadingExperiment: false; skipExperiment: number; totalExperiments: null; searchKey: null ; searchString: null; sortKey: EXPERIMENT_SORT_KEY.STATUS; sortAs: EXPERIMENT_SORT_AS.DESCENDING; ... 7 more ...; expPointsAndIds: {}; }' is not assignable to type 'ExperimentState'. 
Object literal may only specify known properties, and 'context' does not exist in type 'ExperimentState'.
```

**Comment by msandbothe** [comment]
Name for CONTEXT was changed to APP_CONTEXT in #80

**Comment by mfugate1** [comment]
I added APP_CONTEXT to staging with the same value as CONTEXT. 1.0.48 still won't start. Any other environment variables I should know about?

**Comment by msandbothe** [comment]
GROUP_TYPES

https://github.com/CarnegieLearningWeb/UpGrade/pull/80/files#diff-d3ff7c7dbc02dbb854a52aef526595e57036c038b4ababd3799b5c1568458bae

**Comment by mfugate1** [comment]
Ok, the backend failing to start was only because of the missing env variables.

The problem is with the test case in local-storage.service.spec.ts 'should load initial state', it needs to be updated to have the same properties in the ExperimentState interface. I tried doing that myself but then it throws a NullInjectorError in another test, so someone else will need to take a look at this.

**Comment by JD2455** [comment]
ack @mfugate1 . I'm fixing prod build and will create a PR in a while.

**Comment by JD2455** [comment]
@mfugate1 I've created a PR #83 to fix the frontend build:prod error. Can you merge and check?
